"""initial schema

Revision ID: cdef8b8f700b
Revises: 
Create Date: 2026-04-13 09:55:18.839747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdef8b8f700b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_acknowledgment_records_colleague_id'), 'acknowledgment_records', ['colleague_id'], unique=False)
    op.create_index(op.f('ix_acknowledgment_records_paper_id'), 'acknowledgment_records', ['paper_id'], unique=False)
    op.create_index(op.f('ix_claim_maps_paper_id'), 'claim_maps', ['paper_id'], unique=False)
    op.create_index(op.f('ix_claim_maps_source_card_id'), 'claim_maps', ['source_card_id'], unique=False)
    op.create_index(op.f('ix_claim_maps_source_snapshot_id'), 'claim_maps', ['source_snapshot_id'], unique=False)
    op.create_index(op.f('ix_claim_maps_verification_status'), 'claim_maps', ['verification_status'], unique=False)
    op.alter_column('collegial_exchanges', 'round_number',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.create_index(op.f('ix_collegial_exchanges_colleague_id'), 'collegial_exchanges', ['colleague_id'], unique=False)
    op.create_index(op.f('ix_collegial_exchanges_session_id'), 'collegial_exchanges', ['session_id'], unique=False)
    op.alter_column('collegial_sessions', 'status',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('collegial_sessions', 'current_round',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('collegial_sessions', 'max_rounds',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('5'))
    op.create_index(op.f('ix_collegial_sessions_paper_id'), 'collegial_sessions', ['paper_id'], unique=False)
    op.create_index(op.f('ix_correction_records_paper_id'), 'correction_records', ['paper_id'], unique=False)
    op.create_index(op.f('ix_drift_threshold_logs_experiment_id'), 'drift_threshold_logs', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_drift_threshold_logs_family_id'), 'drift_threshold_logs', ['family_id'], unique=False)
    op.create_index(op.f('ix_expert_reviews_paper_id'), 'expert_reviews', ['paper_id'], unique=False)
    op.create_index(op.f('ix_failure_records_family_id'), 'failure_records', ['family_id'], unique=False)
    op.create_index(op.f('ix_failure_records_paper_id'), 'failure_records', ['paper_id'], unique=False)
    op.create_index(op.f('ix_failure_type_proposals_experiment_id'), 'failure_type_proposals', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_family_proposals_experiment_id'), 'family_proposals', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_lock_artifacts_family_id'), 'lock_artifacts', ['family_id'], unique=False)
    op.create_index(op.f('ix_lock_artifacts_paper_id'), 'lock_artifacts', ['paper_id'], unique=False)
    op.create_index(op.f('ix_lock_artifacts_superseded_by'), 'lock_artifacts', ['superseded_by'], unique=False)
    op.create_index(op.f('ix_matches_family_id'), 'matches', ['family_id'], unique=False)
    op.create_index(op.f('ix_matches_paper_a_id'), 'matches', ['paper_a_id'], unique=False)
    op.create_index(op.f('ix_matches_paper_b_id'), 'matches', ['paper_b_id'], unique=False)
    op.create_index(op.f('ix_matches_tournament_run_id'), 'matches', ['tournament_run_id'], unique=False)
    op.create_index(op.f('ix_matches_winner_id'), 'matches', ['winner_id'], unique=False)
    op.create_index(op.f('ix_novelty_checks_paper_id'), 'novelty_checks', ['paper_id'], unique=False)
    op.create_index(op.f('ix_papers_category'), 'papers', ['category'], unique=False)
    op.create_index(op.f('ix_papers_family_id'), 'papers', ['family_id'], unique=False)
    op.create_index(op.f('ix_papers_funnel_stage'), 'papers', ['funnel_stage'], unique=False)
    op.create_index(op.f('ix_papers_release_status'), 'papers', ['release_status'], unique=False)
    op.create_index(op.f('ix_papers_secondary_family_id'), 'papers', ['secondary_family_id'], unique=False)
    op.create_index(op.f('ix_papers_source'), 'papers', ['source'], unique=False)
    op.create_index(op.f('ix_papers_status'), 'papers', ['status'], unique=False)
    op.create_index(op.f('ix_prompt_versions_experiment_id'), 'prompt_versions', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_rating_snapshots_family_id'), 'rating_snapshots', ['family_id'], unique=False)
    op.create_index(op.f('ix_rating_snapshots_paper_id'), 'rating_snapshots', ['paper_id'], unique=False)
    op.create_index(op.f('ix_ratings_family_id'), 'ratings', ['family_id'], unique=False)
    op.create_index(op.f('ix_reliability_metrics_family_id'), 'reliability_metrics', ['family_id'], unique=False)
    op.create_index(op.f('ix_reliability_metrics_paper_id'), 'reliability_metrics', ['paper_id'], unique=False)
    op.create_index(op.f('ix_review_layer_configs_experiment_id'), 'review_layer_configs', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_review_layer_configs_family_id'), 'review_layer_configs', ['family_id'], unique=False)
    op.create_index(op.f('ix_reviews_family_id'), 'reviews', ['family_id'], unique=False)
    op.create_index(op.f('ix_reviews_paper_id'), 'reviews', ['paper_id'], unique=False)
    op.create_index(op.f('ix_role_configs_experiment_id'), 'role_configs', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_role_configs_family_id'), 'role_configs', ['family_id'], unique=False)
    op.create_index(op.f('ix_role_configs_prompt_version_id'), 'role_configs', ['prompt_version_id'], unique=False)
    op.create_index(op.f('ix_rsi_experiments_family_id'), 'rsi_experiments', ['family_id'], unique=False)
    op.create_index(op.f('ix_rsi_gate_logs_experiment_id'), 'rsi_gate_logs', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_significance_memos_paper_id'), 'significance_memos', ['paper_id'], unique=False)
    op.create_index(op.f('ix_source_cards_tier'), 'source_cards', ['tier'], unique=False)
    op.create_index(op.f('ix_source_snapshots_source_card_id'), 'source_snapshots', ['source_card_id'], unique=False)
    op.create_index(op.f('ix_submission_outcomes_paper_id'), 'submission_outcomes', ['paper_id'], unique=False)
    op.create_index(op.f('ix_tournament_runs_family_id'), 'tournament_runs', ['family_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tournament_runs_family_id'), table_name='tournament_runs')
    op.drop_index(op.f('ix_submission_outcomes_paper_id'), table_name='submission_outcomes')
    op.drop_index(op.f('ix_source_snapshots_source_card_id'), table_name='source_snapshots')
    op.drop_index(op.f('ix_source_cards_tier'), table_name='source_cards')
    op.drop_index(op.f('ix_significance_memos_paper_id'), table_name='significance_memos')
    op.drop_index(op.f('ix_rsi_gate_logs_experiment_id'), table_name='rsi_gate_logs')
    op.drop_index(op.f('ix_rsi_experiments_family_id'), table_name='rsi_experiments')
    op.drop_index(op.f('ix_role_configs_prompt_version_id'), table_name='role_configs')
    op.drop_index(op.f('ix_role_configs_family_id'), table_name='role_configs')
    op.drop_index(op.f('ix_role_configs_experiment_id'), table_name='role_configs')
    op.drop_index(op.f('ix_reviews_paper_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_family_id'), table_name='reviews')
    op.drop_index(op.f('ix_review_layer_configs_family_id'), table_name='review_layer_configs')
    op.drop_index(op.f('ix_review_layer_configs_experiment_id'), table_name='review_layer_configs')
    op.drop_index(op.f('ix_reliability_metrics_paper_id'), table_name='reliability_metrics')
    op.drop_index(op.f('ix_reliability_metrics_family_id'), table_name='reliability_metrics')
    op.drop_index(op.f('ix_ratings_family_id'), table_name='ratings')
    op.drop_index(op.f('ix_rating_snapshots_paper_id'), table_name='rating_snapshots')
    op.drop_index(op.f('ix_rating_snapshots_family_id'), table_name='rating_snapshots')
    op.drop_index(op.f('ix_prompt_versions_experiment_id'), table_name='prompt_versions')
    op.drop_index(op.f('ix_papers_status'), table_name='papers')
    op.drop_index(op.f('ix_papers_source'), table_name='papers')
    op.drop_index(op.f('ix_papers_secondary_family_id'), table_name='papers')
    op.drop_index(op.f('ix_papers_release_status'), table_name='papers')
    op.drop_index(op.f('ix_papers_funnel_stage'), table_name='papers')
    op.drop_index(op.f('ix_papers_family_id'), table_name='papers')
    op.drop_index(op.f('ix_papers_category'), table_name='papers')
    op.drop_index(op.f('ix_novelty_checks_paper_id'), table_name='novelty_checks')
    op.drop_index(op.f('ix_matches_winner_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_tournament_run_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_paper_b_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_paper_a_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_family_id'), table_name='matches')
    op.drop_index(op.f('ix_lock_artifacts_superseded_by'), table_name='lock_artifacts')
    op.drop_index(op.f('ix_lock_artifacts_paper_id'), table_name='lock_artifacts')
    op.drop_index(op.f('ix_lock_artifacts_family_id'), table_name='lock_artifacts')
    op.drop_index(op.f('ix_family_proposals_experiment_id'), table_name='family_proposals')
    op.drop_index(op.f('ix_failure_type_proposals_experiment_id'), table_name='failure_type_proposals')
    op.drop_index(op.f('ix_failure_records_paper_id'), table_name='failure_records')
    op.drop_index(op.f('ix_failure_records_family_id'), table_name='failure_records')
    op.drop_index(op.f('ix_expert_reviews_paper_id'), table_name='expert_reviews')
    op.drop_index(op.f('ix_drift_threshold_logs_family_id'), table_name='drift_threshold_logs')
    op.drop_index(op.f('ix_drift_threshold_logs_experiment_id'), table_name='drift_threshold_logs')
    op.drop_index(op.f('ix_correction_records_paper_id'), table_name='correction_records')
    op.drop_index(op.f('ix_collegial_sessions_paper_id'), table_name='collegial_sessions')
    op.alter_column('collegial_sessions', 'max_rounds',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('5'))
    op.alter_column('collegial_sessions', 'current_round',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('collegial_sessions', 'status',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    op.drop_index(op.f('ix_collegial_exchanges_session_id'), table_name='collegial_exchanges')
    op.drop_index(op.f('ix_collegial_exchanges_colleague_id'), table_name='collegial_exchanges')
    op.alter_column('collegial_exchanges', 'round_number',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('ix_claim_maps_verification_status'), table_name='claim_maps')
    op.drop_index(op.f('ix_claim_maps_source_snapshot_id'), table_name='claim_maps')
    op.drop_index(op.f('ix_claim_maps_source_card_id'), table_name='claim_maps')
    op.drop_index(op.f('ix_claim_maps_paper_id'), table_name='claim_maps')
    op.drop_index(op.f('ix_acknowledgment_records_paper_id'), table_name='acknowledgment_records')
    op.drop_index(op.f('ix_acknowledgment_records_colleague_id'), table_name='acknowledgment_records')
    # ### end Alembic commands ###
