"""initial schema

Revision ID: cdef8b8f700b
Revises:
Create Date: 2026-04-28 09:26:10.510686

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cdef8b8f700b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "colleague_profiles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("expertise_area", sa.String(length=64), nullable=False),
        sa.Column("perspective_description", sa.Text(), nullable=False),
        sa.Column("system_prompt", sa.Text(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "domain_configs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("data_sources", sa.Text(), nullable=True),
        sa.Column("analysis_tool", sa.String(length=32), nullable=False),
        sa.Column("evaluation_criteria", sa.Text(), nullable=True),
        sa.Column("review_models", sa.Text(), nullable=True),
        sa.Column("judge_model", sa.String(length=128), nullable=False),
        sa.Column("generation_model", sa.String(length=128), nullable=False),
        sa.Column("categories", sa.Text(), nullable=True),
        sa.Column("countries", sa.Text(), nullable=True),
        sa.Column("methods", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "meta_pipeline_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("observation_json", sa.Text(), nullable=True),
        sa.Column("proposals_json", sa.Text(), nullable=True),
        sa.Column("shadow_results_json", sa.Text(), nullable=True),
        sa.Column("promotion_decision", sa.String(length=16), nullable=True),
        sa.Column("production_delta_json", sa.Text(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "paper_families",
        sa.Column("id", sa.String(length=8), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("short_name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("lock_protocol_type", sa.String(length=64), nullable=False),
        sa.Column("canonical_questions", sa.Text(), nullable=True),
        sa.Column("accepted_methods", sa.Text(), nullable=True),
        sa.Column("public_data_sources", sa.Text(), nullable=True),
        sa.Column("novelty_threshold", sa.Text(), nullable=True),
        sa.Column("venue_ladder", sa.Text(), nullable=True),
        sa.Column("mandatory_checks", sa.Text(), nullable=True),
        sa.Column("fatal_failures", sa.Text(), nullable=True),
        sa.Column("elite_ceiling", sa.Text(), nullable=True),
        sa.Column("benchmark_config", sa.Text(), nullable=True),
        sa.Column("review_rubric", sa.Text(), nullable=True),
        sa.Column("max_portfolio_share", sa.Float(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "source_cards",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("tier", sa.String(length=1), nullable=False),
        sa.Column("source_type", sa.String(length=64), nullable=False),
        sa.Column("temporal_coverage", sa.Text(), nullable=True),
        sa.Column("geographic_coverage", sa.Text(), nullable=True),
        sa.Column("update_frequency", sa.String(length=64), nullable=True),
        sa.Column("access_method", sa.String(length=32), nullable=False),
        sa.Column("requires_key", sa.Boolean(), nullable=False),
        sa.Column("legal_basis", sa.Text(), nullable=True),
        sa.Column("canonical_unit", sa.String(length=128), nullable=True),
        sa.Column("claim_permissions", sa.Text(), nullable=False),
        sa.Column("claim_prohibitions", sa.Text(), nullable=False),
        sa.Column("required_corroboration", sa.Text(), nullable=True),
        sa.Column("parse_method", sa.String(length=64), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("fragility_score", sa.Float(), nullable=False),
        sa.Column("retention_policy", sa.Text(), nullable=True),
        sa.Column("known_traps", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_source_cards_tier"), "source_cards", ["tier"], unique=False
    )
    op.create_table(
        "papers",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("abstract", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=True),
        sa.Column("country", sa.String(length=64), nullable=True),
        sa.Column("method", sa.String(length=64), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("family_id", sa.String(length=8), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("review_status", sa.String(length=32), nullable=False),
        sa.Column("paper_pdf_path", sa.Text(), nullable=True),
        sa.Column("paper_tex_path", sa.Text(), nullable=True),
        sa.Column("code_path", sa.Text(), nullable=True),
        sa.Column("data_path", sa.Text(), nullable=True),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.Column("lock_hash", sa.String(length=64), nullable=True),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.Column("lock_timestamp", sa.DateTime(), nullable=True),
        sa.Column("release_status", sa.String(length=32), nullable=False),
        sa.Column("funnel_stage", sa.String(length=32), nullable=False),
        sa.Column("secondary_family_id", sa.String(length=8), nullable=True),
        sa.Column("idea_card_yaml", sa.Text(), nullable=True),
        sa.Column("novelty_score", sa.Float(), nullable=True),
        sa.Column("data_adequacy_score", sa.Float(), nullable=True),
        sa.Column("venue_fit_score", sa.Float(), nullable=True),
        sa.Column("overall_screening_score", sa.Float(), nullable=True),
        sa.Column("kill_reason", sa.Text(), nullable=True),
        sa.Column("data_question_cluster", sa.String(length=128), nullable=True),
        sa.Column("domain_config_id", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["paper_families.id"],
        ),
        sa.ForeignKeyConstraint(
            ["secondary_family_id"],
            ["paper_families.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_papers_category"), "papers", ["category"], unique=False)
    op.create_index(op.f("ix_papers_family_id"), "papers", ["family_id"], unique=False)
    op.create_index(
        op.f("ix_papers_funnel_stage"), "papers", ["funnel_stage"], unique=False
    )
    op.create_index(
        op.f("ix_papers_release_status"), "papers", ["release_status"], unique=False
    )
    op.create_index(
        op.f("ix_papers_secondary_family_id"),
        "papers",
        ["secondary_family_id"],
        unique=False,
    )
    op.create_index(op.f("ix_papers_source"), "papers", ["source"], unique=False)
    op.create_index(op.f("ix_papers_status"), "papers", ["status"], unique=False)
    op.create_table(
        "rsi_experiments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tier", sa.String(length=8), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("cohort_id", sa.String(length=64), nullable=True),
        sa.Column("family_id", sa.String(length=8), nullable=True),
        sa.Column("created_by", sa.String(length=64), nullable=False),
        sa.Column(
            "proposed_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("activated_at", sa.DateTime(), nullable=True),
        sa.Column("rolled_back_at", sa.DateTime(), nullable=True),
        sa.Column("config_snapshot_json", sa.Text(), nullable=True),
        sa.Column("result_summary_json", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["paper_families.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rsi_experiments_family_id"),
        "rsi_experiments",
        ["family_id"],
        unique=False,
    )
    op.create_table(
        "source_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_card_id", sa.String(length=64), nullable=False),
        sa.Column("snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("snapshot_path", sa.Text(), nullable=False),
        sa.Column("file_size_bytes", sa.Integer(), nullable=True),
        sa.Column("record_count", sa.Integer(), nullable=True),
        sa.Column("fetch_parameters", sa.Text(), nullable=True),
        sa.Column(
            "fetched_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("verified_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_card_id"],
            ["source_cards.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_source_snapshots_source_card_id"),
        "source_snapshots",
        ["source_card_id"],
        unique=False,
    )
    op.create_table(
        "tournament_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("total_matches", sa.Integer(), nullable=False),
        sa.Column("total_batches", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("family_id", sa.String(length=8), nullable=True),
        sa.Column("papers_in_pool", sa.Integer(), nullable=False),
        sa.Column("benchmark_papers", sa.Integer(), nullable=False),
        sa.Column("ai_papers", sa.Integer(), nullable=False),
        sa.Column("judge_calibration_score", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["paper_families.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tournament_runs_family_id"),
        "tournament_runs",
        ["family_id"],
        unique=False,
    )
    op.create_table(
        "acknowledgment_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("paper_id", sa.String(length=64), nullable=False),
        sa.Column("colleague_id", sa.Integer(), nullable=False),
        sa.Column("contribution_type", sa.String(length=32), nullable=False),
        sa.Column("contribution_summary", sa.Text(), nullable=False),
        sa.Column("exchanges_count", sa.Integer(), nullable=False),
        sa.Column("accepted_suggestions", sa.Integer(), nullable=False),
        sa.Column("acknowledgment_text", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["colleague_id"],
            ["colleague_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_acknowledgment_records_colleague_id"),
        "acknowledgment_records",
        ["colleague_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_acknowledgment_records_paper_id"),
        "acknowledgment_records",
        ["paper_id"],
        unique=False,
    )
    op.create_table(
        "autonomy_cards",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("paper_id", sa.String(length=64), nullable=False),
        sa.Column("role_autonomy_json", sa.Text(), nullable=False),
        sa.Column("human_intervention_points_json", sa.Text(), nullable=True),
        sa.Column("overall_autonomy_score", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("paper_id"),
    )
    op.create_table(
        "claim_maps",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("paper_id", sa.String(length=64), nullable=False),
        sa.Column("claim_text", sa.Text(), nullable=False),
        sa.Column("claim_type", sa.String(length=32), nullable=False),
        sa.Column("source_card_id", sa.String(length=64), nullable=True),
        sa.Column("source_snapshot_id", sa.Integer(), nullable=True),
        sa.Column("source_span_ref", sa.Text(), nullable=True),
        sa.Column("result_object_ref", sa.Text(), nullable=True),
        sa.Column("verification_status", sa.String(length=32), nullable=False),
        sa.Column("verified_by", sa.String(length=128), nullable=True),
        sa.Column("verified_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_card_id"],
            ["source_cards.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_snapshot_id"],
            ["source_snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_claim_maps_paper_id"), "claim_maps", ["paper_id"], unique=False
    )
    op.create_index(
        op.f("ix_claim_maps_source_card_id"),
        "claim_maps",
        ["source_card_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_claim_maps_source_snapshot_id"),
        "claim_maps",
        ["source_snapshot_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_claim_maps_verification_status"),
        "claim_maps",
        ["verification_status"],
        unique=False,
    )
    op.create_table(
        "cohort_tags",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("paper_id", sa.String(length=64), nullable=False),
        sa.Column("cohort_id", sa.String(length=64), nullable=False),
        sa.Column("generation_model", sa.String(length=128), nullable=False),
        sa.Column("review_models_json", sa.Text(), nullable=True),
        sa.Column("tournament_judge_model", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("paper_id"),
    )
    op.create_table(
        "collegial_sessions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("paper_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("colleague_ids_json", sa.Text(), nullable=False),
        sa.Column("manuscript_snapshot", sa.Text(), nullable=True),
        sa.Column("total_exchanges", sa.Integer(), nullable=False),
        sa.Column("suggestions_accepted", sa.Integer(), nullable=False),
        sa.Column("suggestions_rejected", sa.Integer(), nullable=False),
        sa.Column("suggestions_partially_incorporated", sa.Integer(), nullable=False),
        sa.Column("session_summary", sa.Text(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("current_round", sa.Integer(), nullable=False),
        sa.Column("max_rounds", sa.Integer(), nullable=False),
        sa.Column("target_venue", sa.String(length=256), nullable=True),
        sa.Column("quality_trajectory_json", sa.Text(), nullable=True),
        sa.Column("final_quality_score", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_collegial_sessions_paper_id"),
        "collegial_sessions",
        ["paper_id"],
        unique=False,
    )
    op.create_table(
        "correction_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("paper_id", sa.String(length=64), nullable=False),
        sa.Column("correction_type", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("affected_claims_json", sa.Text(), nullable=True),
        sa.Column("corrected_at", sa.DateTime(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_correction_records_paper_id"),
        "correction_records",
        ["paper_id"],
        unique=False,
    )
    op.create_table(
        "drift_threshold_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("family_id", sa.String(length=8), nullable=True),
        sa.Column("previous_threshold", sa.Float(), nullable=False),
        sa.Column("new_threshold", sa.Float(), nullable=False),
        sa.Column("gate_block_rate", sa.Float(), nullable=False),
        sa.Column("downstream_failure_rate", sa.Float(), nullable=False),
        sa.Column("experiment_id", sa.Integer(), nullable=True),
        sa.Column(
            "adjusted_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["rsi_experiments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["paper_families.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_drift_threshold_logs_experiment_id"),
        "drift_threshold_logs",
        ["experiment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_drift_threshold_logs_family_id"),
        "drift_threshold_logs",
        ["family_id"],
        unique=False,
    )
    op.create_table(
        "expert_reviews",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("paper_id", sa.String(length=64), nullable=False),
        sa.Column("expert_name", sa.String(length=256), nullable=False),
        sa.Column("affiliation", sa.String(length=256), nullable=True),
        sa.Column("review_date", sa.DateTime(), nullable=False),
        sa.Column("overall_score", sa.Integer(), nullable=False),
        sa.Column("methodology_score", sa.Integer(), nullable=True),
        sa.Column("contribution_score", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_pre_submission", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_expert_reviews_paper_id"), "expert_reviews", ["paper_id"], unique=False
    )
    op.create_table(
        "failure_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("paper_id", sa.String(length=64), nullable=True),
        sa.Column("family_id", sa.String(length=8), nullable=True),
        sa.Column("failure_type", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("detection_stage", sa.String(length=32), nullable=False),
        sa.Column("root_cause_category", sa.String(length=64), nullable=True),
        sa.Column("resolution", sa.Text(), nullable=True),
        sa.Column("corrective_action", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["paper_families.id"],
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_failure_records_family_id"),
        "failure_records",
        ["family_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_failure_records_paper_id"),
        "failure_records",
        ["paper_id"],
        unique=False,
    )
    op.create_table(
        "failure_type_proposals",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("proposed_type_name", sa.String(length=32), nullable=False),
        sa.Column("proposed_description", sa.Text(), nullable=True),
        sa.Column("source_records_json", sa.Text(), nullable=True),
        sa.Column("cluster_size", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("experiment_id", sa.Integer(), nullable=True),
        sa.Column("approved_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["rsi_experiments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_failure_type_proposals_experiment_id"),
        "failure_type_proposals",
        ["experiment_id"],
        unique=False,
    )
    op.create_table(
        "family_proposals",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("proposed_name", sa.String(length=256), nullable=False),
        sa.Column("proposed_short_name", sa.String(length=64), nullable=False),
        sa.Column("proposed_description", sa.Text(), nullable=True),
        sa.Column("source_cluster_json", sa.Text(), nullable=True),
        sa.Column("kill_reasons_json", sa.Text(), nullable=True),
        sa.Column("estimated_viability_score", sa.Float(), nullable=True),
        sa.Column("experiment_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("resulting_family_id", sa.String(length=8), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["rsi_experiments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_family_proposals_experiment_id"),
        "family_proposals",
        ["experiment_id"],
        unique=False,
    )
    op.create_table(
        "lock_artifacts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("paper_id", sa.String(length=64), nullable=False),
        sa.Column("family_id", sa.String(length=8), nullable=False),
        sa.Column("lock_protocol_type", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("lock_hash", sa.String(length=64), nullable=False),
        sa.Column("lock_yaml", sa.Text(), nullable=False),
        sa.Column("narrative_memo", sa.Text(), nullable=True),
        sa.Column("source_manifest_hash", sa.String(length=64), nullable=True),
        sa.Column("immutable_fields", sa.Text(), nullable=False),
        sa.Column("mutable_fields", sa.Text(), nullable=True),
        sa.Column(
            "locked_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("locked_by", sa.String(length=128), nullable=True),
        sa.Column("superseded_by", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["paper_families.id"],
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by"],
            ["lock_artifacts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_lock_artifacts_family_id"),
        "lock_artifacts",
        ["family_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lock_artifacts_paper_id"), "lock_artifacts", ["paper_id"], unique=False
    )
    op.create_index(
        op.f("ix_lock_artifacts_superseded_by"),
        "lock_artifacts",
        ["superseded_by"],
        unique=False,
    )
    op.create_table(
        "matches",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tournament_run_id", sa.Integer(), nullable=False),
        sa.Column("paper_a_id", sa.String(length=64), nullable=False),
        sa.Column("paper_b_id", sa.String(length=64), nullable=False),
        sa.Column("winner_id", sa.String(length=64), nullable=True),
        sa.Column("judge_model", sa.String(length=128), nullable=False),
        sa.Column("judge_prompt", sa.Text(), nullable=True),
        sa.Column("judgment_a_first", sa.Text(), nullable=True),
        sa.Column("judgment_b_first", sa.Text(), nullable=True),
        sa.Column("result_a_first", sa.String(length=16), nullable=True),
        sa.Column("result_b_first", sa.String(length=16), nullable=True),
        sa.Column("final_result", sa.String(length=16), nullable=False),
        sa.Column("batch_number", sa.Integer(), nullable=False),
        sa.Column("mu_change_a", sa.Float(), nullable=True),
        sa.Column("mu_change_b", sa.Float(), nullable=True),
        sa.Column("elo_change_a", sa.Float(), nullable=True),
        sa.Column("elo_change_b", sa.Float(), nullable=True),
        sa.Column("family_id", sa.String(length=8), nullable=True),
        sa.Column("integrity_penalty_a", sa.Boolean(), nullable=False),
        sa.Column("integrity_penalty_b", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["paper_families.id"],
        ),
        sa.ForeignKeyConstraint(
            ["paper_a_id"],
            ["papers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["paper_b_id"],
            ["papers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tournament_run_id"],
            ["tournament_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["winner_id"],
            ["papers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_matches_family_id"), "matches", ["family_id"], unique=False
    )
    op.create_index(
        op.f("ix_matches_paper_a_id"), "matches", ["paper_a_id"], unique=False
    )
    op.create_index(
        op.f("ix_matches_paper_b_id"), "matches", ["paper_b_id"], unique=False
    )
    op.create_index(
        op.f("ix_matches_tournament_run_id"),
        "matches",
        ["tournament_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_matches_winner_id"), "matches", ["winner_id"], unique=False
    )
    op.create_table(
        "novelty_checks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("paper_id", sa.String(length=64), nullable=False),
        sa.Column("checked_against_count", sa.Integer(), nullable=False),
        sa.Column("highest_similarity_score", sa.Float(), nullable=False),
        sa.Column("similar_paper_ids_json", sa.Text(), nullable=True),
        sa.Column("verdict", sa.String(length=16), nullable=False),
        sa.Column("model_used", sa.String(length=128), nullable=False),
        sa.Column("check_details_json", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_novelty_checks_paper_id"), "novelty_checks", ["paper_id"], unique=False
    )
    op.create_table(
        "paper_packages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("paper_id", sa.String(length=64), nullable=False),
        sa.Column("manifest_hash", sa.String(length=64), nullable=False),
        sa.Column("package_path", sa.Text(), nullable=False),
        sa.Column("lock_artifact_hash", sa.String(length=64), nullable=True),
        sa.Column("source_manifest_hash", sa.String(length=64), nullable=True),
        sa.Column("code_hash", sa.String(length=64), nullable=True),
        sa.Column("result_hash", sa.String(length=64), nullable=True),
        sa.Column("manuscript_hash", sa.String(length=64), nullable=True),
        sa.Column("version_major", sa.Integer(), nullable=False),
        sa.Column("version_minor", sa.Integer(), nullable=False),
        sa.Column("version_patch", sa.Integer(), nullable=False),
        sa.Column("authorship_declaration", sa.Text(), nullable=True),
        sa.Column("ai_contribution_log", sa.Text(), nullable=True),
        sa.Column("disclosure_text", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("verified_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("paper_id"),
    )
    op.create_table(
        "prompt_versions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("target_type", sa.String(length=32), nullable=False),
        sa.Column("target_key", sa.String(length=128), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("prompt_text", sa.Text(), nullable=False),
        sa.Column("diff_from_previous", sa.Text(), nullable=True),
        sa.Column("experiment_id", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("performance_json", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["rsi_experiments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_prompt_versions_experiment_id"),
        "prompt_versions",
        ["experiment_id"],
        unique=False,
    )
    op.create_table(
        "rating_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("paper_id", sa.String(length=64), nullable=False),
        sa.Column("mu", sa.Float(), nullable=False),
        sa.Column("sigma", sa.Float(), nullable=False),
        sa.Column("conservative_rating", sa.Float(), nullable=False),
        sa.Column("elo", sa.Float(), nullable=False),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("family_id", sa.String(length=8), nullable=True),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["paper_families.id"],
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rating_snapshots_family_id"),
        "rating_snapshots",
        ["family_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rating_snapshots_paper_id"),
        "rating_snapshots",
        ["paper_id"],
        unique=False,
    )
    op.create_table(
        "ratings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("paper_id", sa.String(length=64), nullable=False),
        sa.Column("mu", sa.Float(), nullable=False),
        sa.Column("sigma", sa.Float(), nullable=False),
        sa.Column("conservative_rating", sa.Float(), nullable=False),
        sa.Column("elo", sa.Float(), nullable=False),
        sa.Column("matches_played", sa.Integer(), nullable=False),
        sa.Column("wins", sa.Integer(), nullable=False),
        sa.Column("losses", sa.Integer(), nullable=False),
        sa.Column("draws", sa.Integer(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column("rank_change_48h", sa.Integer(), nullable=False),
        sa.Column("confidence_lower", sa.Float(), nullable=True),
        sa.Column("confidence_upper", sa.Float(), nullable=True),
        sa.Column("family_id", sa.String(length=8), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["paper_families.id"],
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("paper_id"),
    )
    op.create_index(
        op.f("ix_ratings_family_id"), "ratings", ["family_id"], unique=False
    )
    op.create_table(
        "reliability_metrics",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("paper_id", sa.String(length=64), nullable=True),
        sa.Column("family_id", sa.String(length=8), nullable=True),
        sa.Column("metric_type", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("threshold", sa.Float(), nullable=True),
        sa.Column("passes_threshold", sa.Boolean(), nullable=False),
        sa.Column(
            "computed_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("details_json", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["paper_families.id"],
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reliability_metrics_family_id"),
        "reliability_metrics",
        ["family_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reliability_metrics_paper_id"),
        "reliability_metrics",
        ["paper_id"],
        unique=False,
    )
    op.create_table(
        "review_layer_configs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("layer_name", sa.String(length=32), nullable=False),
        sa.Column("family_id", sa.String(length=8), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("bypass_condition_json", sa.Text(), nullable=True),
        sa.Column("shadow_results_json", sa.Text(), nullable=True),
        sa.Column("effectiveness_score", sa.Float(), nullable=True),
        sa.Column("experiment_id", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["rsi_experiments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["paper_families.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_review_layer_configs_experiment_id"),
        "review_layer_configs",
        ["experiment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_review_layer_configs_family_id"),
        "review_layer_configs",
        ["family_id"],
        unique=False,
    )
    op.create_table(
        "reviews",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("paper_id", sa.String(length=64), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("model_used", sa.String(length=128), nullable=False),
        sa.Column("verdict", sa.String(length=32), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("iteration", sa.Integer(), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("resolution_status", sa.String(length=16), nullable=False),
        sa.Column("family_id", sa.String(length=8), nullable=True),
        sa.Column("review_rubric_version", sa.String(length=32), nullable=True),
        sa.Column("issues_json", sa.Text(), nullable=True),
        sa.Column("resolution_notes", sa.Text(), nullable=True),
        sa.Column("policy_scores_json", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["paper_families.id"],
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reviews_family_id"), "reviews", ["family_id"], unique=False
    )
    op.create_index(op.f("ix_reviews_paper_id"), "reviews", ["paper_id"], unique=False)
    op.create_table(
        "rsi_gate_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("experiment_id", sa.Integer(), nullable=False),
        sa.Column("gate_type", sa.String(length=32), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("metric_before_json", sa.Text(), nullable=True),
        sa.Column("metric_after_json", sa.Text(), nullable=True),
        sa.Column("threshold_json", sa.Text(), nullable=True),
        sa.Column(
            "decided_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["rsi_experiments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rsi_gate_logs_experiment_id"),
        "rsi_gate_logs",
        ["experiment_id"],
        unique=False,
    )
    op.create_table(
        "significance_memos",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("paper_id", sa.String(length=64), nullable=False),
        sa.Column("author", sa.String(length=128), nullable=False),
        sa.Column("memo_text", sa.Text(), nullable=False),
        sa.Column("tournament_rank_at_time", sa.Integer(), nullable=True),
        sa.Column("tournament_confidence_json", sa.Text(), nullable=True),
        sa.Column("editorial_verdict", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_significance_memos_paper_id"),
        "significance_memos",
        ["paper_id"],
        unique=False,
    )
    op.create_table(
        "submission_outcomes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("paper_id", sa.String(length=64), nullable=False),
        sa.Column("venue_name", sa.String(length=256), nullable=False),
        sa.Column("submitted_date", sa.DateTime(), nullable=False),
        sa.Column("decision", sa.String(length=32), nullable=True),
        sa.Column("decision_date", sa.DateTime(), nullable=True),
        sa.Column("revision_rounds", sa.Integer(), nullable=False),
        sa.Column("reviewer_feedback_summary", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_submission_outcomes_paper_id"),
        "submission_outcomes",
        ["paper_id"],
        unique=False,
    )
    op.create_table(
        "collegial_exchanges",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("colleague_id", sa.Integer(), nullable=True),
        sa.Column("speaker_role", sa.String(length=16), nullable=False),
        sa.Column("turn_number", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("exchange_type", sa.String(length=32), nullable=False),
        sa.Column("target_section", sa.String(length=64), nullable=True),
        sa.Column("referenced_claims", sa.Text(), nullable=True),
        sa.Column("round_number", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["colleague_id"],
            ["colleague_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["collegial_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_collegial_exchanges_colleague_id"),
        "collegial_exchanges",
        ["colleague_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_collegial_exchanges_session_id"),
        "collegial_exchanges",
        ["session_id"],
        unique=False,
    )
    op.create_table(
        "role_configs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("role_name", sa.String(length=64), nullable=False),
        sa.Column("parent_role", sa.String(length=64), nullable=True),
        sa.Column("family_id", sa.String(length=8), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("capabilities_json", sa.Text(), nullable=True),
        sa.Column("boundaries_json", sa.Text(), nullable=True),
        sa.Column("prerequisite_stages_json", sa.Text(), nullable=True),
        sa.Column("prompt_version_id", sa.Integer(), nullable=True),
        sa.Column("experiment_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["rsi_experiments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["paper_families.id"],
        ),
        sa.ForeignKeyConstraint(
            ["prompt_version_id"],
            ["prompt_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_role_configs_experiment_id"),
        "role_configs",
        ["experiment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_role_configs_family_id"), "role_configs", ["family_id"], unique=False
    )
    op.create_index(
        op.f("ix_role_configs_prompt_version_id"),
        "role_configs",
        ["prompt_version_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_role_configs_prompt_version_id"), table_name="role_configs")
    op.drop_index(op.f("ix_role_configs_family_id"), table_name="role_configs")
    op.drop_index(op.f("ix_role_configs_experiment_id"), table_name="role_configs")
    op.drop_table("role_configs")
    op.drop_index(
        op.f("ix_collegial_exchanges_session_id"), table_name="collegial_exchanges"
    )
    op.drop_index(
        op.f("ix_collegial_exchanges_colleague_id"), table_name="collegial_exchanges"
    )
    op.drop_table("collegial_exchanges")
    op.drop_index(
        op.f("ix_submission_outcomes_paper_id"), table_name="submission_outcomes"
    )
    op.drop_table("submission_outcomes")
    op.drop_index(
        op.f("ix_significance_memos_paper_id"), table_name="significance_memos"
    )
    op.drop_table("significance_memos")
    op.drop_index(op.f("ix_rsi_gate_logs_experiment_id"), table_name="rsi_gate_logs")
    op.drop_table("rsi_gate_logs")
    op.drop_index(op.f("ix_reviews_paper_id"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_family_id"), table_name="reviews")
    op.drop_table("reviews")
    op.drop_index(
        op.f("ix_review_layer_configs_family_id"), table_name="review_layer_configs"
    )
    op.drop_index(
        op.f("ix_review_layer_configs_experiment_id"), table_name="review_layer_configs"
    )
    op.drop_table("review_layer_configs")
    op.drop_index(
        op.f("ix_reliability_metrics_paper_id"), table_name="reliability_metrics"
    )
    op.drop_index(
        op.f("ix_reliability_metrics_family_id"), table_name="reliability_metrics"
    )
    op.drop_table("reliability_metrics")
    op.drop_index(op.f("ix_ratings_family_id"), table_name="ratings")
    op.drop_table("ratings")
    op.drop_index(op.f("ix_rating_snapshots_paper_id"), table_name="rating_snapshots")
    op.drop_index(op.f("ix_rating_snapshots_family_id"), table_name="rating_snapshots")
    op.drop_table("rating_snapshots")
    op.drop_index(
        op.f("ix_prompt_versions_experiment_id"), table_name="prompt_versions"
    )
    op.drop_table("prompt_versions")
    op.drop_table("paper_packages")
    op.drop_index(op.f("ix_novelty_checks_paper_id"), table_name="novelty_checks")
    op.drop_table("novelty_checks")
    op.drop_index(op.f("ix_matches_winner_id"), table_name="matches")
    op.drop_index(op.f("ix_matches_tournament_run_id"), table_name="matches")
    op.drop_index(op.f("ix_matches_paper_b_id"), table_name="matches")
    op.drop_index(op.f("ix_matches_paper_a_id"), table_name="matches")
    op.drop_index(op.f("ix_matches_family_id"), table_name="matches")
    op.drop_table("matches")
    op.drop_index(op.f("ix_lock_artifacts_superseded_by"), table_name="lock_artifacts")
    op.drop_index(op.f("ix_lock_artifacts_paper_id"), table_name="lock_artifacts")
    op.drop_index(op.f("ix_lock_artifacts_family_id"), table_name="lock_artifacts")
    op.drop_table("lock_artifacts")
    op.drop_index(
        op.f("ix_family_proposals_experiment_id"), table_name="family_proposals"
    )
    op.drop_table("family_proposals")
    op.drop_index(
        op.f("ix_failure_type_proposals_experiment_id"),
        table_name="failure_type_proposals",
    )
    op.drop_table("failure_type_proposals")
    op.drop_index(op.f("ix_failure_records_paper_id"), table_name="failure_records")
    op.drop_index(op.f("ix_failure_records_family_id"), table_name="failure_records")
    op.drop_table("failure_records")
    op.drop_index(op.f("ix_expert_reviews_paper_id"), table_name="expert_reviews")
    op.drop_table("expert_reviews")
    op.drop_index(
        op.f("ix_drift_threshold_logs_family_id"), table_name="drift_threshold_logs"
    )
    op.drop_index(
        op.f("ix_drift_threshold_logs_experiment_id"), table_name="drift_threshold_logs"
    )
    op.drop_table("drift_threshold_logs")
    op.drop_index(
        op.f("ix_correction_records_paper_id"), table_name="correction_records"
    )
    op.drop_table("correction_records")
    op.drop_index(
        op.f("ix_collegial_sessions_paper_id"), table_name="collegial_sessions"
    )
    op.drop_table("collegial_sessions")
    op.drop_table("cohort_tags")
    op.drop_index(op.f("ix_claim_maps_verification_status"), table_name="claim_maps")
    op.drop_index(op.f("ix_claim_maps_source_snapshot_id"), table_name="claim_maps")
    op.drop_index(op.f("ix_claim_maps_source_card_id"), table_name="claim_maps")
    op.drop_index(op.f("ix_claim_maps_paper_id"), table_name="claim_maps")
    op.drop_table("claim_maps")
    op.drop_table("autonomy_cards")
    op.drop_index(
        op.f("ix_acknowledgment_records_paper_id"), table_name="acknowledgment_records"
    )
    op.drop_index(
        op.f("ix_acknowledgment_records_colleague_id"),
        table_name="acknowledgment_records",
    )
    op.drop_table("acknowledgment_records")
    op.drop_index(op.f("ix_tournament_runs_family_id"), table_name="tournament_runs")
    op.drop_table("tournament_runs")
    op.drop_index(
        op.f("ix_source_snapshots_source_card_id"), table_name="source_snapshots"
    )
    op.drop_table("source_snapshots")
    op.drop_index(op.f("ix_rsi_experiments_family_id"), table_name="rsi_experiments")
    op.drop_table("rsi_experiments")
    op.drop_index(op.f("ix_papers_status"), table_name="papers")
    op.drop_index(op.f("ix_papers_source"), table_name="papers")
    op.drop_index(op.f("ix_papers_secondary_family_id"), table_name="papers")
    op.drop_index(op.f("ix_papers_release_status"), table_name="papers")
    op.drop_index(op.f("ix_papers_funnel_stage"), table_name="papers")
    op.drop_index(op.f("ix_papers_family_id"), table_name="papers")
    op.drop_index(op.f("ix_papers_category"), table_name="papers")
    op.drop_table("papers")
    op.drop_index(op.f("ix_source_cards_tier"), table_name="source_cards")
    op.drop_table("source_cards")
    op.drop_table("paper_families")
    op.drop_table("meta_pipeline_runs")
    op.drop_table("domain_configs")
    op.drop_table("colleague_profiles")
    # ### end Alembic commands ###
