import html
import logging
import uuid
from datetime import UTC, datetime
from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException, Query, Request
from fastapi.responses import FileResponse, Response
from slowapi import Limiter
from slowapi.util import get_remote_address
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.auth import admin_key_required
from app.config import settings
from app.database import get_db
from app.models.paper import Paper
from app.models.rating import Rating
from app.schemas.paper import PaperCreate, PaperImport, PaperResponse, PaperWithRating

limiter = Limiter(key_func=get_remote_address)
router = APIRouter()
logger = logging.getLogger(__name__)


def generate_paper_id() -> str:
    count = uuid.uuid4().hex[:8]
    return f"apep_{count}"


@router.get("/papers", response_model=list[PaperWithRating])
async def list_papers(
    source: str | None = Query(None, max_length=64),
    category: str | None = Query(None, max_length=64),
    country: str | None = Query(None, max_length=64),
    status: str | None = Query(None, max_length=32),
    limit: int = Query(50, ge=1, le=250),
    offset: int = Query(0, ge=0),
    db: AsyncSession = Depends(get_db),
):
    query = select(Paper).outerjoin(Rating, Paper.id == Rating.paper_id)

    if source:
        query = query.where(Paper.source == source)
    if category:
        query = query.where(Paper.category == category)
    if country:
        query = query.where(Paper.country == country)
    if status:
        query = query.where(Paper.status == status)

    query = query.order_by(Paper.created_at.desc()).offset(offset).limit(limit)
    results = (await db.execute(query)).scalars().unique().all()

    papers = []
    for paper in results:
        data = PaperWithRating.model_validate(paper)
        if paper.rating:
            data.mu = paper.rating.mu
            data.sigma = paper.rating.sigma
            data.conservative_rating = paper.rating.conservative_rating
            data.elo = paper.rating.elo
            data.matches_played = paper.rating.matches_played
            data.rank = paper.rating.rank
            data.rank_change_48h = paper.rating.rank_change_48h
        papers.append(data)

    return papers


# ---------------------------------------------------------------------------
# Public feed (no auth — GET endpoints bypass MutationAuthMiddleware)
# Must be defined BEFORE /papers/{paper_id} to avoid wildcard capture.
# ---------------------------------------------------------------------------

@router.get("/papers/public")
async def list_public_papers(
    limit: int = Query(50, ge=1, le=250),
    offset: int = Query(0, ge=0),
    db: AsyncSession = Depends(get_db),
):
    """Return papers that have reached candidate or public release status."""
    query = (
        select(Paper)
        .where(Paper.release_status.in_(["candidate", "submitted", "public"]))
        .where(Paper.status != "killed")
        .order_by(Paper.created_at.desc())
        .offset(offset)
        .limit(limit)
    )
    papers = (await db.execute(query)).scalars().all()

    return [
        {
            "id": p.id,
            "title": p.title,
            "abstract": p.abstract,
            "family_id": p.family_id,
            "release_status": p.release_status,
            "funnel_stage": p.funnel_stage,
            "category": p.category,
            "method": p.method,
            "novelty_score": p.novelty_score,
            "overall_screening_score": p.overall_screening_score,
            "created_at": p.created_at.isoformat() if p.created_at else None,
        }
        for p in papers
    ]


@router.get("/papers/feed.json")
async def paper_json_feed(
    limit: int = Query(20, ge=1, le=100),
    db: AsyncSession = Depends(get_db),
):
    """JSON Feed (v1.1) of published/candidate papers for external consumption."""
    query = (
        select(Paper)
        .where(Paper.release_status.in_(["candidate", "submitted", "public"]))
        .where(Paper.status != "killed")
        .order_by(Paper.created_at.desc())
        .limit(limit)
    )
    papers = (await db.execute(query)).scalars().all()

    items = []
    for p in papers:
        items.append({
            "id": p.id,
            "title": p.title,
            "content_text": p.abstract or "",
            "date_published": p.created_at.isoformat() if p.created_at else None,
            "_ari": {
                "family_id": p.family_id,
                "release_status": p.release_status,
                "method": p.method,
                "novelty_score": p.novelty_score,
            },
        })

    return {
        "version": "https://jsonfeed.org/version/1.1",
        "title": "ARI — Autonomous Research Infrastructure",
        "description": "Papers generated by the autonomous research pipeline",
        "items": items,
    }


@router.get("/papers/feed.atom")
async def paper_atom_feed(
    request: Request,
    limit: int = Query(20, ge=1, le=100),
    db: AsyncSession = Depends(get_db),
):
    """Atom 1.0 feed of published/candidate papers for academic subscribers.

    The Atom format is widely supported by reference managers (Zotero, Mendeley)
    and feed readers, making it the canonical subscription surface for
    researchers tracking new AI-generated papers.
    """
    query = (
        select(Paper)
        .where(Paper.release_status.in_(["candidate", "submitted", "public"]))
        .where(Paper.status != "killed")
        .order_by(Paper.created_at.desc())
        .limit(limit)
    )
    papers = (await db.execute(query)).scalars().all()

    base_url = str(request.base_url).rstrip("/")
    feed_url = f"{base_url}/api/v1/papers/feed.atom"
    site_url = base_url.replace("/api/v1", "")  # frontend root if behind same host

    updated = (
        max((p.created_at for p in papers if p.created_at), default=None)
        or datetime.now(UTC)
    )

    def esc(s: str | None) -> str:
        return html.escape(s or "", quote=True)

    entries: list[str] = []
    for p in papers:
        published = (p.created_at or updated).isoformat()
        category = (
            f'<category term="{esc(p.method)}" />' if p.method else ""
        )
        novelty = (
            f"<ari:novelty_score>{p.novelty_score:.3f}</ari:novelty_score>"
            if p.novelty_score is not None
            else ""
        )
        entries.append(
            f"""  <entry>
    <id>urn:ari:paper:{esc(p.id)}</id>
    <title>{esc(p.title)}</title>
    <link rel="alternate" type="text/html" href="{site_url}/papers/{esc(p.id)}" />
    <published>{published}</published>
    <updated>{published}</updated>
    <author><name>Autonomous Research Infrastructure</name></author>
    <summary type="text">{esc(p.abstract or "")}</summary>
    {category}
    <ari:family>{esc(p.family_id)}</ari:family>
    <ari:release_status>{esc(p.release_status)}</ari:release_status>
    {novelty}
  </entry>"""
        )

    body = (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<feed xmlns="http://www.w3.org/2005/Atom" '
        'xmlns:ari="https://ari.example.com/atom-extensions">\n'
        f"  <id>urn:ari:feed</id>\n"
        f"  <title>ARI — Autonomous Research Infrastructure</title>\n"
        f"  <subtitle>Papers generated by the autonomous research pipeline</subtitle>\n"
        f'  <link rel="self" type="application/atom+xml" href="{feed_url}" />\n'
        f'  <link rel="alternate" type="text/html" href="{site_url}/publications" />\n'
        f"  <updated>{updated.isoformat()}</updated>\n"
        + "\n".join(entries)
        + "\n</feed>\n"
    )

    return Response(content=body, media_type="application/atom+xml")


@router.get("/papers/{paper_id}", response_model=PaperWithRating)
async def get_paper(paper_id: str, db: AsyncSession = Depends(get_db)):
    paper = (
        await db.execute(
            select(Paper).where(Paper.id == paper_id)
        )
    ).scalar_one_or_none()

    if not paper:
        raise HTTPException(status_code=404, detail="Paper not found")

    data = PaperWithRating.model_validate(paper)
    if paper.rating:
        data.mu = paper.rating.mu
        data.sigma = paper.rating.sigma
        data.conservative_rating = paper.rating.conservative_rating
        data.elo = paper.rating.elo
        data.matches_played = paper.rating.matches_played
        data.rank = paper.rating.rank
        data.rank_change_48h = paper.rating.rank_change_48h

    return data


@router.get("/papers/{paper_id}/export")
async def export_paper(
    paper_id: str,
    format: str = Query("pdf", pattern="^(pdf|tex)$"),
    db: AsyncSession = Depends(get_db),
):
    """Download the compiled PDF or TeX source for a paper."""
    paper = (
        await db.execute(select(Paper).where(Paper.id == paper_id))
    ).scalar_one_or_none()

    if not paper:
        raise HTTPException(status_code=404, detail="Paper not found")

    if format == "pdf":
        path = paper.paper_pdf_path
        media_type = "application/pdf"
    else:
        path = paper.paper_tex_path
        media_type = "application/x-tex"

    if not path:
        raise HTTPException(
            status_code=404,
            detail=f"No {format.upper()} artifact available for this paper",
        )

    file_path = Path(path)
    if not file_path.is_file():
        raise HTTPException(
            status_code=404,
            detail=f"{format.upper()} file not found on disk",
        )

    return FileResponse(
        path=str(file_path),
        media_type=media_type,
        filename=f"{paper_id}.{format}",
    )


@router.post("/papers", response_model=PaperResponse)
async def create_paper(paper_in: PaperCreate, db: AsyncSession = Depends(get_db)):
    paper_id = paper_in.id or generate_paper_id()

    paper = Paper(
        id=paper_id,
        title=paper_in.title,
        abstract=paper_in.abstract,
        source=paper_in.source,
        category=paper_in.category,
        country=paper_in.country,
        method=paper_in.method,
        version=paper_in.version,
        status="published",
        review_status="awaiting",
        domain_config_id=paper_in.domain_config_id,
    )
    db.add(paper)

    rating = Rating(
        paper_id=paper_id,
        mu=settings.trueskill_mu,
        sigma=settings.trueskill_sigma,
        conservative_rating=settings.trueskill_mu - 3 * settings.trueskill_sigma,
        elo=settings.elo_default,
    )
    db.add(rating)

    try:
        await db.commit()
        await db.refresh(paper)
    except Exception:
        await db.rollback()
        logger.exception("Failed to create paper")
        raise HTTPException(status_code=500, detail="Failed to create paper")
    return PaperResponse.model_validate(paper)


@router.post(
    "/papers/import",
    response_model=list[PaperResponse],
    dependencies=[Depends(admin_key_required)],
)
@limiter.limit("10/hour")
async def import_papers(request: Request, data: PaperImport, db: AsyncSession = Depends(get_db)):
    created = []
    # Pre-generate IDs and batch-check existence to avoid N+1
    candidate_ids = [p.id or generate_paper_id() for p in data.papers]
    existing_result = await db.execute(
        select(Paper.id).where(Paper.id.in_(candidate_ids))
    )
    existing_ids = set(existing_result.scalars().all())

    for paper_in, paper_id in zip(data.papers, candidate_ids):
        if paper_id in existing_ids:
            continue

        paper = Paper(
            id=paper_id,
            title=paper_in.title,
            abstract=paper_in.abstract,
            source=paper_in.source,
            category=paper_in.category,
            country=paper_in.country,
            method=paper_in.method,
            version=paper_in.version,
            status="published",
            review_status="peer_reviewed" if paper_in.source in ("aer", "aej_policy", "benchmark") else "awaiting",
            domain_config_id=paper_in.domain_config_id,
        )
        db.add(paper)

        rating = Rating(
            paper_id=paper_id,
            mu=settings.trueskill_mu,
            sigma=settings.trueskill_sigma,
            conservative_rating=settings.trueskill_mu - 3 * settings.trueskill_sigma,
            elo=settings.elo_default,
        )
        db.add(rating)
        created.append(paper)

    try:
        await db.commit()
        for p in created:
            await db.refresh(p)
    except Exception:
        await db.rollback()
        logger.exception("Failed to import papers (batch of %d)", len(data.papers))
        raise HTTPException(status_code=500, detail="Failed to import papers")

    return [PaperResponse.model_validate(p) for p in created]
