import logging
import uuid
from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException, Query, Request
from fastapi.responses import FileResponse
from slowapi import Limiter
from slowapi.util import get_remote_address
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.auth import admin_key_required
from app.config import settings
from app.database import get_db
from app.models.paper import Paper
from app.models.rating import Rating
from app.schemas.paper import PaperCreate, PaperImport, PaperResponse, PaperWithRating

limiter = Limiter(key_func=get_remote_address)
router = APIRouter()
logger = logging.getLogger(__name__)


def generate_paper_id() -> str:
    count = uuid.uuid4().hex[:8]
    return f"apep_{count}"


@router.get("/papers", response_model=list[PaperWithRating])
async def list_papers(
    source: str | None = Query(None, max_length=64),
    category: str | None = Query(None, max_length=64),
    country: str | None = Query(None, max_length=64),
    status: str | None = Query(None, max_length=32),
    limit: int = Query(50, ge=1, le=250),
    offset: int = Query(0, ge=0),
    db: AsyncSession = Depends(get_db),
):
    query = select(Paper).outerjoin(Rating, Paper.id == Rating.paper_id)

    if source:
        query = query.where(Paper.source == source)
    if category:
        query = query.where(Paper.category == category)
    if country:
        query = query.where(Paper.country == country)
    if status:
        query = query.where(Paper.status == status)

    query = query.order_by(Paper.created_at.desc()).offset(offset).limit(limit)
    results = (await db.execute(query)).scalars().unique().all()

    papers = []
    for paper in results:
        data = PaperWithRating.model_validate(paper)
        if paper.rating:
            data.mu = paper.rating.mu
            data.sigma = paper.rating.sigma
            data.conservative_rating = paper.rating.conservative_rating
            data.elo = paper.rating.elo
            data.matches_played = paper.rating.matches_played
            data.rank = paper.rating.rank
            data.rank_change_48h = paper.rating.rank_change_48h
        papers.append(data)

    return papers


# ---------------------------------------------------------------------------
# Public feed (no auth — GET endpoints bypass MutationAuthMiddleware)
# Must be defined BEFORE /papers/{paper_id} to avoid wildcard capture.
# ---------------------------------------------------------------------------


@router.get("/papers/public")
async def list_public_papers(
    limit: int = Query(50, ge=1, le=250),
    offset: int = Query(0, ge=0),
    db: AsyncSession = Depends(get_db),
):
    """Return papers that have reached candidate or public release status."""
    query = (
        select(Paper)
        .where(Paper.release_status.in_(["candidate", "submitted", "public"]))
        .where(Paper.status != "killed")
        .order_by(Paper.created_at.desc())
        .offset(offset)
        .limit(limit)
    )
    papers = (await db.execute(query)).scalars().all()

    return [
        {
            "id": p.id,
            "title": p.title,
            "abstract": p.abstract,
            "family_id": p.family_id,
            "release_status": p.release_status,
            "funnel_stage": p.funnel_stage,
            "category": p.category,
            "method": p.method,
            "novelty_score": p.novelty_score,
            "overall_screening_score": p.overall_screening_score,
            "created_at": p.created_at.isoformat() if p.created_at else None,
        }
        for p in papers
    ]


@router.get("/papers/feed.json")
async def paper_json_feed(
    limit: int = Query(20, ge=1, le=100),
    db: AsyncSession = Depends(get_db),
):
    """JSON Feed (v1.1) of published/candidate papers for external consumption."""
    query = (
        select(Paper)
        .where(Paper.release_status.in_(["candidate", "submitted", "public"]))
        .where(Paper.status != "killed")
        .order_by(Paper.created_at.desc())
        .limit(limit)
    )
    papers = (await db.execute(query)).scalars().all()

    items = []
    for p in papers:
        items.append(
            {
                "id": p.id,
                "title": p.title,
                "content_text": p.abstract or "",
                "date_published": p.created_at.isoformat() if p.created_at else None,
                "_ari": {
                    "family_id": p.family_id,
                    "release_status": p.release_status,
                    "method": p.method,
                    "novelty_score": p.novelty_score,
                },
            }
        )

    return {
        "version": "https://jsonfeed.org/version/1.1",
        "title": "ARI — Autonomous Research Infrastructure",
        "description": "Papers generated by the autonomous research pipeline",
        "items": items,
    }


@router.get("/papers/{paper_id}", response_model=PaperWithRating)
async def get_paper(paper_id: str, db: AsyncSession = Depends(get_db)):
    paper = (await db.execute(select(Paper).where(Paper.id == paper_id))).scalar_one_or_none()

    if not paper:
        raise HTTPException(status_code=404, detail="Paper not found")

    data = PaperWithRating.model_validate(paper)
    if paper.rating:
        data.mu = paper.rating.mu
        data.sigma = paper.rating.sigma
        data.conservative_rating = paper.rating.conservative_rating
        data.elo = paper.rating.elo
        data.matches_played = paper.rating.matches_played
        data.rank = paper.rating.rank
        data.rank_change_48h = paper.rating.rank_change_48h

    # Surface parsed error_message from the orchestrator's metadata_json
    # blob so failed papers can be diagnosed without backend log access.
    if paper.status == "error" and paper.metadata_json:
        try:
            import json as _json

            metadata = _json.loads(paper.metadata_json)
            data.error_message = metadata.get("error")
        except (_json.JSONDecodeError, TypeError):
            data.error_message = paper.metadata_json[:500]

    return data


@router.get("/papers/{paper_id}/export")
async def export_paper(
    paper_id: str,
    format: str = Query("pdf", pattern="^(pdf|tex)$"),
    db: AsyncSession = Depends(get_db),
):
    """Download the compiled PDF or TeX source for a paper.

    For ``format=tex`` the resolution order is:
      1. ``Paper.manuscript_latex`` column — durable copy added in PR #58.
         Used preferentially because Render's ephemeral filesystem wipes
         the .tex file at ``paper_tex_path`` on every redeploy.
      2. ``paper_tex_path`` file on disk — fallback for pre-PR-58 papers.

    For ``format=pdf`` only the disk path is checked (PDFs aren't
    generated yet in this pipeline; reserved for future use).
    """
    from fastapi.responses import Response

    paper = (await db.execute(select(Paper).where(Paper.id == paper_id))).scalar_one_or_none()

    if not paper:
        raise HTTPException(status_code=404, detail="Paper not found")

    # TeX: prefer the durable DB column; fall back to disk.
    if format == "tex":
        if paper.manuscript_latex:
            return Response(
                content=paper.manuscript_latex,
                media_type="application/x-tex",
                headers={"Content-Disposition": f'attachment; filename="{paper_id}.tex"'},
            )

        # Fallback: read from disk for pre-PR-58 papers.
        if paper.paper_tex_path:
            file_path = Path(paper.paper_tex_path)
            if file_path.is_file():
                return FileResponse(
                    path=str(file_path),
                    media_type="application/x-tex",
                    filename=f"{paper_id}.tex",
                )

        raise HTTPException(
            status_code=404,
            detail=(
                "No TEX artifact available for this paper. "
                "DB copy is empty and the on-disk file is missing "
                "(likely wiped by a Render redeploy)."
            ),
        )

    # PDF: only the disk path is checked.
    if not paper.paper_pdf_path:
        raise HTTPException(
            status_code=404,
            detail="No PDF artifact available for this paper",
        )

    file_path = Path(paper.paper_pdf_path)
    if not file_path.is_file():
        raise HTTPException(
            status_code=404,
            detail="PDF file not found on disk",
        )

    return FileResponse(
        path=str(file_path),
        media_type="application/pdf",
        filename=f"{paper_id}.pdf",
    )


@router.post(
    "/admin/papers/{paper_id}/backfill-title",
    response_model=PaperResponse,
    dependencies=[Depends(admin_key_required)],
)
async def backfill_paper_title(paper_id: str, db: AsyncSession = Depends(get_db)):
    """Re-derive paper.title from the saved manuscript LaTeX.

    Necessary for papers created before PR #30 landed the
    title-extraction fix. Production paper apep_faf874ae completed
    end-to-end (8 stages, 26 sourced claims) but its title still
    reads ``"Generating..."`` because the Drafter ran with the
    placeholder code. This endpoint re-extracts ``\\title{...}`` from
    the manuscript stored on the PaperPackage's package_path.

    Idempotent — running it on a paper whose title is already
    populated is a no-op (returns the existing record).
    """
    from pathlib import Path

    from sqlalchemy.orm import selectinload

    from app.services.paper_generation.roles.drafter import _extract_latex_title

    paper = (
        await db.execute(
            select(Paper).where(Paper.id == paper_id).options(selectinload(Paper.package))
        )
    ).scalar_one_or_none()
    if not paper:
        raise HTTPException(status_code=404, detail="Paper not found")

    if paper.title and paper.title != "Generating...":
        # Already has a real title — nothing to do.
        return PaperResponse.model_validate(paper)

    if paper.package is None:
        raise HTTPException(
            status_code=400,
            detail=(
                f"Paper {paper_id} has no PaperPackage record — "
                "manuscript artifact location unknown."
            ),
        )

    package_path = Path(paper.package.package_path)
    candidates = [
        package_path / "manuscript.tex",
        package_path / "paper.tex",
        package_path / "main.tex",
    ]
    manuscript_path = next((p for p in candidates if p.is_file()), None)
    if manuscript_path is None:
        raise HTTPException(
            status_code=404,
            detail=(
                f"No manuscript file found at {package_path} "
                f"(tried: {[p.name for p in candidates]}). "
                "Artifact may have been wiped during a Render redeploy."
            ),
        )

    manuscript_latex = manuscript_path.read_text(encoding="utf-8", errors="replace")
    title = _extract_latex_title(manuscript_latex)
    if not title:
        raise HTTPException(
            status_code=400,
            detail=("Manuscript file exists but contains no extractable \\title{...} block."),
        )

    paper.title = title
    db.add(paper)
    await db.commit()
    await db.refresh(paper)

    logger.info(
        "Backfilled title for paper %s from %s: %r",
        paper_id,
        manuscript_path,
        title,
    )

    return PaperResponse.model_validate(paper)


@router.post(
    "/admin/papers/{paper_id}/backfill-manuscript",
    dependencies=[Depends(admin_key_required)],
)
async def backfill_manuscript_latex(paper_id: str, db: AsyncSession = Depends(get_db)):
    """Read manuscript content from disk and copy it into ``Paper.manuscript_latex``.

    Useful for papers generated before PR #58 deployed — they have
    ``paper_tex_path`` set but ``manuscript_latex`` is NULL. This
    endpoint reads from the path (if the file still exists) and stores
    the content in the DB column so it survives future Render redeploys.

    Idempotent: papers that already have ``manuscript_latex`` populated
    return immediately. Papers with no on-disk file return 404 — the
    artifact is unrecoverable (wiped by a prior redeploy before this
    endpoint existed).
    """
    paper = (await db.execute(select(Paper).where(Paper.id == paper_id))).scalar_one_or_none()
    if not paper:
        raise HTTPException(status_code=404, detail="Paper not found")

    if paper.manuscript_latex:
        return {
            "paper_id": paper_id,
            "status": "already_populated",
            "length": len(paper.manuscript_latex),
        }

    if not paper.paper_tex_path:
        raise HTTPException(
            status_code=404,
            detail=("No paper_tex_path on this paper — manuscript was never written to disk."),
        )

    file_path = Path(paper.paper_tex_path)
    if not file_path.is_file():
        raise HTTPException(
            status_code=404,
            detail=(
                "Manuscript file not found on disk (likely wiped by a "
                "prior Render redeploy). Content is unrecoverable; the "
                "paper would have to be regenerated."
            ),
        )

    content = file_path.read_text(encoding="utf-8", errors="replace")
    paper.manuscript_latex = content
    db.add(paper)
    await db.commit()

    logger.info(
        "Backfilled manuscript_latex for paper %s from %s (%d chars)",
        paper_id,
        file_path,
        len(content),
    )
    return {
        "paper_id": paper_id,
        "status": "backfilled",
        "length": len(content),
    }


@router.post(
    "/admin/papers/reap-orphans",
    dependencies=[Depends(admin_key_required)],
)
async def reap_orphan_papers(
    stale_minutes: int = Query(
        30, ge=5, le=240,
        description="Heartbeat staleness threshold in minutes. Default 30.",
    ),
    db: AsyncSession = Depends(get_db),
):
    """Find papers stuck at non-terminal status with stale heartbeats and
    flip them to ``status='killed'``.

    Production paper apep_f237bfc0 (autonomous-loop run 25207115248) is
    the canonical case: created at 07:51:27, last_heartbeat from
    Analyst at 07:54:35, then 42 minutes of silence until the workflow
    timed out. The Analyst stage's 900s asyncio.timeout (PR #46) should
    have fired and PR #48's ``_set_killed_at_stage`` should have flipped
    status to killed — but neither did, almost certainly because the
    Render worker process was killed entirely (no Python alive to run
    cleanup).

    PR #46 + #48 require the Python process to survive. This reaper
    closes the gap from the OUTSIDE: at /admin invocation it scans for
    papers whose heartbeat is older than the threshold AND whose status
    is non-terminal. Each match is flipped to ``status='killed'`` with
    ``kill_reason="reaped: stale heartbeat (last seen at <stage> N min ago)"``.

    The cron / a periodic job can call this on every workflow run to
    keep the status field honest.

    Terminal statuses (not reaped):
        candidate, published, error, killed, rejected

    Threshold default 30 min. Drafter is the longest legitimate stage
    at 15 min so 30 min gives 2x safety margin.
    """
    from datetime import datetime, timedelta, timezone

    cutoff = datetime.now(timezone.utc) - timedelta(minutes=stale_minutes)
    cutoff_naive = cutoff.replace(tzinfo=None)

    # Find candidates: non-terminal status with stale (or missing) heartbeat.
    # Papers without any heartbeat at all are also candidates if they're old
    # enough — i.e. the worker died before even writing a heartbeat.
    terminal_statuses = ("candidate", "published", "error", "killed", "rejected")
    stmt = select(Paper).where(
        Paper.status.notin_(terminal_statuses),
        Paper.created_at < cutoff_naive,
    )
    candidates = (await db.execute(stmt)).scalars().all()

    reaped: list[dict] = []
    for paper in candidates:
        # If there's a heartbeat, only reap if it's stale.
        if paper.last_heartbeat_at is not None:
            hb = paper.last_heartbeat_at
            if hb.tzinfo is None:
                hb = hb.replace(tzinfo=timezone.utc)
            hb_naive = hb.replace(tzinfo=None)
            if hb_naive >= cutoff_naive:
                # Heartbeat is fresh — don't reap.
                continue
            stage = paper.last_heartbeat_stage or "unknown"
            staleness_min = int((cutoff_naive - hb_naive).total_seconds() / 60)
            reason = (
                f"reaped: stale heartbeat (last seen at {stage} "
                f"~{staleness_min + stale_minutes} min ago)"
            )
        else:
            # No heartbeat at all — worker probably died before writing one.
            age_min = int((cutoff_naive - paper.created_at).total_seconds() / 60)
            reason = f"reaped: no heartbeat after {age_min} min"

        paper.status = "killed"
        paper.funnel_stage = "killed"
        paper.kill_reason = reason
        paper.review_status = "skipped"
        db.add(paper)
        reaped.append(
            {
                "paper_id": paper.id,
                "previous_status": "draft",  # by predicate
                "previous_funnel_stage": paper.funnel_stage,
                "last_heartbeat_stage": paper.last_heartbeat_stage,
                "kill_reason": reason,
            }
        )

    if reaped:
        await db.commit()
        logger.warning(
            "Reaped %d orphan paper(s) with stale heartbeats (>%d min)",
            len(reaped),
            stale_minutes,
        )

    return {
        "stale_threshold_minutes": stale_minutes,
        "candidates_examined": len(candidates),
        "reaped_count": len(reaped),
        "reaped": reaped,
    }


@router.post(
    "/admin/papers/re-verify-batch",
    dependencies=[Depends(admin_key_required)],
)
async def re_verify_batch(
    min_pending_ratio: float = Query(
        0.2, ge=0.0, le=1.0,
        description="Only re-verify papers with at least this fraction of "
        "claims still at pending status. Default 0.2 (20%).",
    ),
    limit: int = Query(
        10, ge=1, le=50,
        description="Maximum number of papers to re-verify in one call.",
    ),
    db: AsyncSession = Depends(get_db),
):
    """Run the re-verify operation on every paper with high pending count.

    Production observation: every paper that completes generation has
    ~70% of claims stuck at ``verification_status='pending'`` because
    the Verifier LLM cherry-picks per batch (PRs #50/52/53 documented
    this; PR #56 added the per-paper re-verify endpoint as the
    operational workaround).

    Without this batch endpoint, the cron has to query each paper and
    call /re-verify individually. With it, the cron makes one call
    that finds and processes every relevant paper in sequence.

    Selection criteria:
      - status='reviewing' (just completed generation, awaiting review)
      - OR status='candidate' (passed Packager but not yet reviewed)
      - AND pending claim count / total > min_pending_ratio
      - Ordered by created_at DESC (newest first)
      - Capped at ``limit`` papers

    Each paper's re-verify is run sequentially (not in parallel) so
    the LLM concurrency limits don't kick in. Slow but bounded:
    ~2-5 min per paper × ``limit``.

    Returns a summary of papers processed + before/after pending counts.
    """
    from app.models.claim_map import ClaimMap
    from app.services.paper_generation.roles.verifier import verify_manuscript

    candidates = (
        await db.execute(
            select(Paper)
            .where(Paper.status.in_(("reviewing", "candidate")))
            .order_by(Paper.created_at.desc())
            .limit(limit)
        )
    ).scalars().all()

    eligible: list[Paper] = []
    for paper in candidates:
        # Compute pending ratio for this paper.
        claim_rows = (
            await db.execute(
                select(ClaimMap.verification_status).where(
                    ClaimMap.paper_id == paper.id
                )
            )
        ).scalars().all()
        if not claim_rows:
            continue
        pending = sum(1 for s in claim_rows if s == "pending")
        ratio = pending / len(claim_rows)
        if ratio >= min_pending_ratio:
            eligible.append(paper)

    results: list[dict] = []
    for paper in eligible:
        before_pending = (
            await db.execute(
                select(ClaimMap).where(
                    ClaimMap.paper_id == paper.id,
                    ClaimMap.verification_status == "pending",
                )
            )
        ).scalars().all()
        before_count = len(before_pending)

        try:
            await verify_manuscript(paper_id=paper.id, status_filter="pending")
        except ValueError as e:
            results.append({
                "paper_id": paper.id,
                "before_pending": before_count,
                "after_pending": before_count,
                "error": str(e),
            })
            continue
        except Exception as e:
            logger.exception("Re-verify-batch failed for paper %s", paper.id)
            results.append({
                "paper_id": paper.id,
                "before_pending": before_count,
                "after_pending": before_count,
                "error": f"internal: {type(e).__name__}",
            })
            continue

        after_pending = (
            await db.execute(
                select(ClaimMap).where(
                    ClaimMap.paper_id == paper.id,
                    ClaimMap.verification_status == "pending",
                )
            )
        ).scalars().all()
        results.append({
            "paper_id": paper.id,
            "before_pending": before_count,
            "after_pending": len(after_pending),
            "delta": before_count - len(after_pending),
        })

    return {
        "min_pending_ratio": min_pending_ratio,
        "limit": limit,
        "candidates_examined": len(candidates),
        "eligible_count": len(eligible),
        "processed_count": len(results),
        "results": results,
    }


@router.post(
    "/admin/papers/{paper_id}/re-verify",
    dependencies=[Depends(admin_key_required)],
)
async def re_verify_paper_pending_claims(paper_id: str, db: AsyncSession = Depends(get_db)):
    """Re-run the Verifier on claims still at ``verification_status='pending'``.

    Empirical observation across 5 production runs: the Verifier LLM
    cherry-picks which claims to verify regardless of batch size or
    prompt instructions, leaving ~70% of claims at ``pending`` after
    the first pass (PRs #50, #52, #53 documented this behavior).
    PR #54 made partial coverage acceptable by changing L2's
    ``coverage_ratio`` formula, but coverage stays low forever for
    that paper.

    This endpoint provides the missing step: run the Verifier again,
    but only on the claims it dropped on the prior pass. Repeated
    invocations approach 100% coverage incrementally.

    Returns the Verifier's standard report shape (``claim_verifications``
    + ``summary``) plus a ``before`` / ``after`` snapshot of the
    pending count so the operator can see the delta.

    Idempotent in spirit — running it on a paper with zero pending
    claims is a no-op that returns immediately.
    """
    from app.models.claim_map import ClaimMap
    from app.services.paper_generation.roles.verifier import verify_manuscript

    paper = (await db.execute(select(Paper).where(Paper.id == paper_id))).scalar_one_or_none()
    if not paper:
        raise HTTPException(status_code=404, detail="Paper not found")

    pending_before = (
        (
            await db.execute(
                select(ClaimMap).where(
                    ClaimMap.paper_id == paper_id,
                    ClaimMap.verification_status == "pending",
                )
            )
        )
        .scalars()
        .all()
    )

    if not pending_before:
        return {
            "paper_id": paper_id,
            "before": {"pending": 0},
            "after": {"pending": 0},
            "verification": {
                "claim_verifications": [],
                "summary": {
                    "total_claims": 0,
                    "passed": 0,
                    "failed": 0,
                    "warnings": 0,
                    "critical_violations": [],
                    "recommendation": "approve",
                },
            },
            "message": "No pending claims to re-verify.",
        }

    pending_count_before = len(pending_before)

    try:
        report = await verify_manuscript(paper_id=paper_id, status_filter="pending")
    except ValueError as e:
        # Most common: no active lock artifact for this paper.
        raise HTTPException(status_code=400, detail=str(e))
    except Exception:
        logger.exception("Re-verify failed for paper %s", paper_id)
        raise HTTPException(
            status_code=500,
            detail="Verifier re-run encountered an internal error",
        )

    pending_after_count = await db.execute(
        select(ClaimMap).where(
            ClaimMap.paper_id == paper_id,
            ClaimMap.verification_status == "pending",
        )
    )
    pending_count_after = len(pending_after_count.scalars().all())

    logger.info(
        "Re-verified paper %s: pending %d → %d (delta=%d)",
        paper_id,
        pending_count_before,
        pending_count_after,
        pending_count_before - pending_count_after,
    )

    return {
        "paper_id": paper_id,
        "before": {"pending": pending_count_before},
        "after": {"pending": pending_count_after},
        "verification": report,
    }


@router.post("/papers", response_model=PaperResponse)
async def create_paper(paper_in: PaperCreate, db: AsyncSession = Depends(get_db)):
    paper_id = paper_in.id or generate_paper_id()

    paper = Paper(
        id=paper_id,
        title=paper_in.title,
        abstract=paper_in.abstract,
        source=paper_in.source,
        category=paper_in.category,
        country=paper_in.country,
        method=paper_in.method,
        version=paper_in.version,
        status="published",
        review_status="awaiting",
        domain_config_id=paper_in.domain_config_id,
    )
    db.add(paper)

    rating = Rating(
        paper_id=paper_id,
        mu=settings.trueskill_mu,
        sigma=settings.trueskill_sigma,
        conservative_rating=settings.trueskill_mu - 3 * settings.trueskill_sigma,
        elo=settings.elo_default,
    )
    db.add(rating)

    try:
        await db.commit()
        await db.refresh(paper)
    except Exception:
        await db.rollback()
        logger.exception("Failed to create paper")
        raise HTTPException(status_code=500, detail="Failed to create paper")
    return PaperResponse.model_validate(paper)


@router.post(
    "/papers/import",
    response_model=list[PaperResponse],
    dependencies=[Depends(admin_key_required)],
)
@limiter.limit("10/hour")
async def import_papers(request: Request, data: PaperImport, db: AsyncSession = Depends(get_db)):
    created = []
    # Pre-generate IDs and batch-check existence to avoid N+1
    candidate_ids = [p.id or generate_paper_id() for p in data.papers]
    existing_result = await db.execute(select(Paper.id).where(Paper.id.in_(candidate_ids)))
    existing_ids = set(existing_result.scalars().all())

    for paper_in, paper_id in zip(data.papers, candidate_ids):
        if paper_id in existing_ids:
            continue

        paper = Paper(
            id=paper_id,
            title=paper_in.title,
            abstract=paper_in.abstract,
            source=paper_in.source,
            category=paper_in.category,
            country=paper_in.country,
            method=paper_in.method,
            version=paper_in.version,
            status="published",
            review_status="peer_reviewed"
            if paper_in.source in ("aer", "aej_policy", "benchmark")
            else "awaiting",
            domain_config_id=paper_in.domain_config_id,
        )
        db.add(paper)

        rating = Rating(
            paper_id=paper_id,
            mu=settings.trueskill_mu,
            sigma=settings.trueskill_sigma,
            conservative_rating=settings.trueskill_mu - 3 * settings.trueskill_sigma,
            elo=settings.elo_default,
        )
        db.add(rating)
        created.append(paper)

    try:
        await db.commit()
        for p in created:
            await db.refresh(p)
    except Exception:
        await db.rollback()
        logger.exception("Failed to import papers (batch of %d)", len(data.papers))
        raise HTTPException(status_code=500, detail="Failed to import papers")

    return [PaperResponse.model_validate(p) for p in created]
